general:
steps:
  mtaBuild:
    buildTarget: 'CF'
    mtaBuildTool: 'cloudMbt'
    defaultNpmRegistry: 'https://registry.npmjs.org/'
    postBuildAction: 'mbt --version'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: 's0019621851trial'
      space: 'dev'
      credentialsId: 'CF_CREDENTIALSID'

