general:
steps:
  mtaBuild:
    buildTarget: 'CF'
    dockerImage: 'devxci/mbtci:latest'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: 's0019621851trial'
      space: 'dev'
      credentialsId: 'CF_CREDENTIALSID'
