general:
steps:
  mtaBuild:
    buildTarget: 'CF'
    defaultNpmRegistry: 'https://npm.sap.com'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: 's0019621851trial'
      space: 'dev'
      credentialsId: 'CF_CREDENTIALSID'
